server
{
    listen 80 default_server;
    server_name _ 8.134.169.227;
    index index.html;
    root /www/wwwroot/yingyu;

    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

    access_log  /www/wwwlogs/yingyu.access.log;
    error_log   /www/wwwlogs/yingyu.error.log;
}
