server
{
    listen 80;
    listen [::]:80;
    server_name en.nextlong.cn;

    location ^~ /.well-known/acme-challenge/ {
        root /www/wwwroot/yingyu;
        allow all;
    }

    return 301 https://$host$request_uri;
}

server
{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name en.nextlong.cn;

    index index.html index.htm;
    root /www/wwwroot/yingyu;
    charset utf-8;

    ssl_certificate /etc/letsencrypt/live/en.nextlong.cn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/en.nextlong.cn/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    access_log /www/wwwlogs/en.nextlong.cn.log;
    error_log /www/wwwlogs/en.nextlong.cn.error.log;
}
