server
{
    listen 80;
    listen [::]:80;
    server_name en.nextlong.cn;

    index index.html index.htm;
    root /www/wwwroot/yingyu;
    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    access_log /www/wwwlogs/en.nextlong.cn.log;
    error_log /www/wwwlogs/en.nextlong.cn.error.log;
}
